const CONFIG = {
    SUPABASE_URL: 'https://ocdloxagawjkokiheuiu.supabase.co',
    SUPABASE_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9jZGxveGFnYXdqa29raWhldWl1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1MTM1NTQsImV4cCI6MjA2ODA4OTU1NH0.OFC4QyrCKtyY_2JA2I5MnI8JjmuFBYHuJH7nO1Vyu5o',
    GAME_ID: 'main_game',
    VAPID_PUBLIC_KEY: 'BKjbHJM8wMo41SARCuHzrCwE5V6wEDRl_yYYiQ-P9G6FsWbonlmdYZankfzDeKF6gCdo9DZnJxVYPIUTzZBtfVI'
};